// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at ١٨‏/٢‏/٢٠٢٦، ١١:٣١:٠٢ م
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/nawal omar/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/nawal omar/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/nawal omar/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/nawal omar/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/nawal omar/plugins/**/*.{js,ts,mjs}","D:/nawal omar/composables/**/*.{js,ts,mjs}","D:/nawal omar/utils/**/*.{js,ts,mjs}","D:/nawal omar/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/nawal omar/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/nawal omar/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/nawal omar/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;